In [1]:
import numpy as np

In [2]:
np.zeros(12)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
x_list = [i for i in range(12)]
x = np.array(x_list, dtype=np.float64)
print(x)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]


In [9]:
y = np.array([2 for i in range(12)])
print(y)

[2 2 2 2 2 2 2 2 2 2 2 2]


In [6]:
x+y

array([ 1.        ,  1.5       ,  2.33333333,  3.25      ,  4.2       ,
        5.16666667,  6.14285714,  7.125     ,  8.11111111,  9.1       ,
       10.09090909, 11.08333333])

In [7]:
np.mean(x), np.std(y)

(5.5, 0.2520720127993913)

In [8]:
x+1, y*2

(array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]),
 array([2.        , 1.        , 0.66666667, 0.5       , 0.4       ,
        0.33333333, 0.28571429, 0.25      , 0.22222222, 0.2       ,
        0.18181818, 0.16666667]))

In [ ]:
import panda as pd

In [ ]:
fish = pd.read_csv('./Fish.csv')
type(fish)

In [ ]:
for c in fish.columns:
    print(c)